apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: weather-analytics
spec:
  replicas: 1

  selector:
    matchLabels:
      app: airflow-webserver

  template:
    metadata:
      labels:
        app: airflow-webserver

    spec:
      containers:
        - name: airflow-webserver
          image: weather-airflow:2.9.0
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              value: development-secret-key

            - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
              value: "True"

            - name: PYTHONPATH
              value: /opt/airflow

          command:
            - /bin/bash
            - -c

          args:
            - |
              export AIRFLOW__DATABASE__SQL_ALCHEMY_CONN="postgresql+psycopg2://airflow:${POSTGRES_PASSWORD}@postgres:5432/airflow"
              exec airflow webserver

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"

