apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
  namespace: weather-analytics
data:
  01_create_open_meteo.sql: |
    SELECT 'CREATE DATABASE open_meteo'
    WHERE NOT EXISTS (
        SELECT 1
        FROM pg_database
        WHERE datname = 'open_meteo'
    )\gexec

  02_create_superset.sql: |
    SELECT 'CREATE DATABASE superset'
    WHERE NOT EXISTS (
        SELECT 1
        FROM pg_database
        WHERE datname = 'superset'
    )\gexec

