apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-initdb
  namespace: weather-analytics
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: postgres-initdb
          image: postgres:15
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          command:
            - /bin/bash
            - -c
          args:
            - |
              psql -h postgres -U airflow -d airflow -f /initdb/01_create_open_meteo.sql
              psql -h postgres -U airflow -d airflow -f /initdb/02_create_superset.sql
          volumeMounts:
            - name: initdb-scripts
              mountPath: /initdb
      volumes:
        - name: initdb-scripts
          configMap:
            name: postgres-initdb

